---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint ../arillso.hosts
  flake8
platforms:
  - name: ubuntu-xenial
    image: arillso/ubuntu:xenial
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
  env:
    ANSIBLE_ROLES_PATH: ../../
verifier:
  name: ansible
