---
# tasks file for arillso.hosts

- name: "Edits the hosts file in /etc"
  become: true
  ansible.builtin.template:
    src: "etc/hosts.j2"
    dest: "{{ hosts_file }}"
    backup: "{{ hosts_backup }}"
    group: "{{ hosts_group }}"
    owner: "{{ hosts_owner }}"
    serole: "{{ hosts_serole }}"
    setype: "{{ hosts_setype }}"
    seuser: "{{ hosts_seuser }}"
    selevel: "{{ hosts_selevel }}"
    mode: "{{ hosts_mode }}"
  tags:
    - configuration
