---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint ../arillso.hosts
  flake8
platforms:
  - name: alpine-3.11
    image: arillso/alpine:3.11
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: alpine-3.12
    image: arillso/alpine:3.12
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos-7
    image: arillso/centos:7
    privileged: true
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos-8
    image: arillso/centos:8
    privileged: true
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian-10
    image: arillso/debian:10
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian-11
    image: arillso/debian:11
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian-sid
    image: arillso/debian:sid
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu-bionic
    image: arillso/ubuntu:bionic
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu-focal
    image: arillso/ubuntu:focal
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu-xenial
    image: arillso/ubuntu:xenial
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../default/converge.yml
  env:
    ANSIBLE_ROLES_PATH: ../../
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: ansible
