---
name: Lint Code Base

on:
  push:
    branches-ignore: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint Code Base

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANSIBLE_DIRECTORY: /
