---
name: Role Release
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: arillso.hosts

    steps:
      - uses: actions/checkout@v2
        with:
          path: arillso.hosts

      - name: Ansible Molecule Test
        uses: gofrolist/molecule-action@v2.0.1
        with:
          molecule_command: test
          molecule_working_dir: arillso.hosts

  publish:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - release

    steps:
      - name: Release Ansible Role to Galaxy
        uses: hspaans/ansible-galaxy-action@v0.1.1
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
