---
name: Role Release
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    name: Role Release Test

    defaults:
      run:
        working-directory: arillso.hosts

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: arillso.hosts

      - name: Test Ansible with Molecule
        uses: arillso/action.molecule@main
        with:
          command: test
          working_directory: arillso.hosts

  publish:
    runs-on: ubuntu-latest

    name: Role Release Publish

    if: always()
    needs:
      - release

    steps:
      - name: Release Ansible Role to Galaxy
        uses: robertdebock/galaxy-action@1.1.1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
