---
name: Role Tests
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: arillso.hosts
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        scenario:
          - alpine-3.11
          - alpine-3.12
          - centos-7
          - centos-8
          - debian-bullseye
          - debian-buster
          - debian-sid
          - default
          - ubuntu-bionic
          - ubuntu-focal
          - ubuntu-xenial

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          path: arillso.hosts

      - name: Test Ansible with Molecule
        uses: arillso/action.molecule@main
        with:
          command: test
          working_directory: arillso.hosts
          scenario: ${{ matrix.scenario }}
