---
name: Role Tests
on:
  push:
  pull_request:

jobs:
  molecule:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: arillso.hosts
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        scenario:
          - alpine-3.11
          - alpine-3.12
          - centos-7
          - centos-8
          - debian-bullseye
          - debian-buster
          - debian-sid
          - default
          - ubuntu-bionic
          - ubuntu-focal
          - ubuntu-xenial

    steps:
      - uses: actions/checkout@v2
        with:
          path: arillso.hosts

      - name: Ansible Molecule Test
        uses: onaio/molecule-action@master
        with:
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
